# Generated by Django 5.2.3 on 2025-07-01 10:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('SITTING_ANIMAL', 'Sitting Animal'), ('YOGA_BOWLS', 'Yoga Bowls'), ('PER_DAY', 'Per Day'), ('YOGA_ANIMALS', 'Yoga Animals'), ('CHOPSTICK_HOLDERS', 'Chopstick Holders'), ('STANDING_ANIMAL', 'Standing Animal'), ('BOTTLE_CORKS', 'Bottle Corks'), ('SANTA_YOGA_BOWLS', 'Santa Yoga Bowls'), ('SANTA_YOGA_ANIMALS', 'Santa Yoga Animals'), ('HEAD_BOWLS', 'Head Bowls'), ('DRINKING_BOWLS', 'Drinking Bowls'), ('ANIMAL_MASKS', 'Animal Masks'), ('CHOPSTICK_HEADS', 'Chopstick Heads'), ('CHESS_UNITS', 'Chess Units'), ('STOOL_SET', 'Stool Set'), ('SALAD_SERVERS_PAIR', 'Salad Servers (in pairs)'), ('WALKING_ANIMAL', 'Walking Animal'), ('PLACE_CARD_HOLDER', 'Place Card Holder')], max_length=50)),
                ('animal_type', models.CharField(max_length=50)),
                ('service_category', models.CharField(choices=[('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('PAINTING', 'Painting'), ('SANDING', 'Sanding'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50)),
                ('size_category', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('WITH CLOTHES', 'With Clothes'), ('WITH DRESS', 'With Dress'), ('WITH SUIT', 'With Suit'), ('WITH OVERALL', 'With Overall'), ('4IN', '4 Inch'), ('8X8', '8x8'), ('6X6', '6x6'), ('5X4', '5x4'), ('XMAS DRESS', 'Xmas Dress'), ('IN PAIRS', 'In Pairs'), ('12IN', '12 Inch'), ('8IN', '8 Inch'), ('N/A', 'Not Applicable')], default='MEDIUM', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('last_price_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['product_type', 'animal_type', 'service_category'], name='products_pr_product_cb13cd_idx')],
                'unique_together': {('product_type', 'animal_type', 'service_category', 'size_category')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
    ]
