# Generated by Django 4.2.23 on 2025-07-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_product_cb13cd_idx',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_type', 'animal_type', 'size_category')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'animal_type'], name='products_pr_product_2d36b6_idx'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='service_category',
        ),
    ]
