# Generated by Django 4.2.23 on 2025-08-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_products_pr_product_cb13cd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('SITTING_ANIMAL', 'Sitting Animal'), ('YOGA_BOWLS', 'Yoga Bowls'), ('PER_DAY', 'Per Day'), ('YOGA_ANIMALS', 'Yoga Animals'), ('CHOPSTICK_HOLDERS', 'Chopstick Holders'), ('STANDING_ANIMAL', 'Standing Animal'), ('BOTTLE_CORKS', 'Bottle Corks'), ('SANTA_YOGA_BOWLS', 'Santa Yoga Bowls'), ('SANTA_YOGA_ANIMALS', 'Santa Yoga Animals'), ('HEAD_BOWLS', 'Head Bowls'), ('DRINKING_BOWLS', 'Drinking Bowls'), ('ANIMAL_MASKS', 'Animal Masks'), ('CHOPSTICK_HEADS', 'Chopstick Heads'), ('CHESS_UNITS', 'Chess Units'), ('STOOL_SET', 'Stool Set'), ('SALAD_SERVERS_PAIR', 'Salad Servers (in pairs)'), ('WALKING_ANIMAL', 'Walking Animal'), ('PLACE_CARD_HOLDER', 'Place Card Holder'), ('SANTA_ANIMALS', 'Santa Animals'), ('SUGAR_SPOONS', 'Sugar Spoons'), ('COCKTAIL_STICKS', 'Cocktail Sticks'), ('KEY_HOLDERS', 'Key Holders'), ('FLAT_MAGNETS', 'Flat Magnets'), ('PLAY_ANIMALS', 'Play Animals'), ('CHOPSTICKS', 'Chopsticks'), ('X_MAS_DECO', 'X-Mas Deco'), ('FORKS', 'Forks'), ('BUTTER_KNIFE', 'Butter Knife'), ('LETTER_OPENER', 'Letter Opener'), ('JAM_SCOOPERS', 'Jam Scoopers'), ('NAPKIN_HOLDERS', 'Napkin Holders'), ('HAIR_COMBS', 'Hair Combs')], max_length=50),
        ),
    ]
