# Generated by Django 5.2.3 on 2025-07-01 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('service_category', models.CharField(choices=[('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('PAINTING', 'Painting'), ('SANDING', 'Sanding'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('quantity_accepted', models.PositiveIntegerField(default=0)),
                ('rejection_reason', models.CharField(blank=True, choices=[('QUALITY', 'Quality Issues'), ('DAMAGE', 'Damaged Item'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('original_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('final_payment', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('payslip_generated', models.BooleanField(default=False)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artisans.artisan')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jobs.job')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='JobDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField()),
                ('quantity_accepted', models.PositiveIntegerField(default=0)),
                ('rejection_reason', models.CharField(blank=True, choices=[('QUALITY', 'Quality Issues'), ('DAMAGE', 'Damaged Item'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('job_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='jobs.jobitem')),
            ],
        ),
    ]
