# Generated by Django 5.2.3 on 2025-07-08 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Rating from 1.0 to 5.0', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
