# Generated by Django 5.2.3 on 2025-07-01 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(blank=True, choices=[('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('PAINTING', 'Painting'), ('SANDING', 'Sanding'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50, null=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to='payslips/')),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artisans.artisan')),
            ],
        ),
    ]
