# Generated by Django 4.2.23 on 2025-07-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedstock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='finishedstock',
            unique_together={('product',)},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'service_category')},
        ),
        migrations.AddIndex(
            model_name='finishedstock',
            index=models.Index(fields=['product'], name='inventory_f_product_e96990_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedstock',
            index=models.Index(fields=['is_active'], name='inventory_f_is_acti_745bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product', 'service_category'], name='inventory_i_product_d1d4d5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['is_active'], name='inventory_i_is_acti_05630a_idx'),
        ),
    ]
