# Generated by Django 4.2.23 on 2025-07-13 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_finishedstock_is_active_inventory_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='price_at_this_stage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
