# Generated by Django 4.2.23 on 2025-07-13 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_products_pr_product_cb13cd_idx_and_more'),
        ('inventory', '0003_inventory_price_at_this_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='service_category',
            field=models.CharField(choices=[('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('PAINTING', 'Painting'), ('SANDING', 'Sanding'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50),
        ),
    ]
