# Generated by Django 4.2.23 on 2025-07-16 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_products_pr_product_cb13cd_idx_and_more'),
        ('payslips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(choices=[('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('PAINTING', 'Painting'), ('SANDING', 'Sanding'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], help_text='The stage/service category this rate is for (e.g., CARVING, PAINTING).', max_length=50)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, help_text='The rate paid to an artisan per unit of this product for this service category.', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service rate is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The product this service rate applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='payslip_service_rates', to='products.product')),
            ],
            options={
                'verbose_name': 'Service Rate',
                'verbose_name_plural': 'Service Rates',
                'ordering': ['product__product_type', 'product__animal_type', 'service_category'],
                'unique_together': {('product', 'service_category')},
            },
        ),
    ]
