# Generated by Django 4.2.23 on 2025-07-13 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobitem_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(choices=[('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('PAINTING', 'Painting'), ('SANDING', 'Sanding'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50, unique=True)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Service Rate',
                'verbose_name_plural': 'Service Rates',
            },
        ),
    ]
