# Generated by Django 4.2.23 on 2025-07-13 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_products_pr_product_cb13cd_idx_and_more'),
        ('jobs', '0003_servicerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerate',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerate',
            name='service_category',
            field=models.CharField(choices=[('CARVING', 'Carving'), ('CUTTING', 'Cutting'), ('PAINTING', 'Painting'), ('SANDING', 'Sanding'), ('FINISHING', 'Finishing'), ('FINISHED', 'Finished')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='servicerate',
            unique_together={('product', 'service_category')},
        ),
    ]
