# Generated by Django 4.2.23 on 2025-07-16 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_products_pr_product_cb13cd_idx_and_more'),
        ('jobs', '0004_servicerate_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_service_rates', to='products.product'),
        ),
    ]
