# Generated by Django 5.2.3 on 2025-07-08 06:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0001_initial'),
        ('jobs', '0002_jobitem_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('comment', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('job_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_detail', to='jobs.jobitem')),
            ],
        ),
    ]
